export var pokemonGames = 
[
    "Red",
    "Blue",
    "Yellow",
    "Gold",
    "Silver",
    "Crystal",
    "Ruby",
    "Sapphire",
    "Emerald",
    "Fire Red",
    "Leaf Green",
    "Diamond",
    "Pearl",
    "Platinum",
    "Heart Gold",
    "Soul Silver",
    "Black",
    "White",
    "Black 2",
    "White 2",
    "Sun",
    "Moon",
    "Ultra Sun",
    "Utlra Moon",
    "Sword",
    "Shield",
    "Scarlet",
    "Violet"
]